ALTER TABLE channels ADD COLUMN voice_bitrate INTEGER NOT NULL DEFAULT 64000;
ALTER TABLE channels ADD COLUMN voice_user_limit INTEGER NOT NULL DEFAULT 0;
ALTER TABLE channels ADD COLUMN voice_ptt_only INTEGER NOT NULL DEFAULT 0;
